In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [-3, -1, 2],
    [2, 1, 0],
    [-2, 1, 2]
])

A_inv = np.array([
    [2, 4, ],
    [-1, 0, 1],
    [1, 1, 0]
]) * (1/18.)

print(np.linalg.solve(A, b))

print((A) @ np.array([1, -1, 1]))

# eigvals, eigvecs = np.linalg.eig(A)

# eigvecs @ np.linalg.inv(eigvecs)


In [ ]:
Q = np.array([
    [0.707, 0.707],
    [0.707, -0.707]
])

D = np.array([
    [4, 0],
    [0, 2]
])

print(Q@D@Q.T)



In [1]:
s11 = np.array([-3, 2, -2])
s11_norm = s11/np.linalg.norm(s11)

s12 = np.array([-2, 1, -2])
s12 = s12 - s12@s11_norm*s11_norm
s12_norm = s12/np.linalg.norm(s12)

s2 = np.array([1, 1, 0])
s2 = s2 - s2@s11_norm*s11_norm - s2@s12_norm*s12_norm
s2_norm = s2/np.linalg.norm(s2)

print(s11@s12)
print(s11@s2)
print(s12@s2)

print(np.linalg.norm(s11_norm))
print(np.linalg.norm(s12_norm))
print(np.linalg.norm(s2_norm))

print(s11_norm)
print(s12_norm)
print(s2_norm)

NameError: name 'np' is not defined

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([1,1,-1])
v3 = np.array([-5,4,-1])

-5/14*v1+7/3*v2+-17/42*v3

array([ 4.,  0., -3.])

In [ ]:
A = np.array([
    [0, 1, 0],
    [1, 0, 1]
])

# eigvals, V = np.linalg.eig(A.T @ A)

# eigvals[1], eigvals[2] = eigvals[2], eigvals[1]
# V[:, [1, 2]] = V[:, [2, 1]]

# sigmas = np.sqrt(np.round(eigvals, 5))
# sigmas = sigmas[sigmas != 0]

# U = np.zeros((len(A), len(A)))
# for i in range(len(A)):
#     U[i] = 1/sigmas[i] * A @ V[:,i]

# S = np.zeros(A.shape)
# for i in range(len(sigmas)):
#     S[i, i] = sigmas[i]

# print('U=\n', U)
# print('Σ=\n', S)
# print('V=\n', np.round(V, 5))

# print('A-UΣV.T=\n', A - U@S@V.T)


In [ ]:
U, S, VT = np.linalg.svd(A, full_matrices=True)
print(np.linalg.svd(A, full_matrices=True))
# Σ = np.zeros(A.shape)
# for i in range(len(S)):
#     Σ[i, i] = 1/S[i]
# print(np.round(U, 3))
# print(np.round(Σ, 3))
# print(np.round(VT.T, 3))

V = VT.T

Σ = np.array([
    [1/1.414, 0],
    [0, 1],
    [0, 0]
])

UT = U.T

np.round(V @ Σ @ UT, 3)

(array([[0., 1.],
       [1., 0.]]), array([1.41421356, 1.        ]), array([[ 0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678]]))


array([[0. , 0.5],
       [1. , 0. ],
       [0. , 0.5]])

In [ ]:
pinv = np.round(VT.T @ Σ @ U.T)

print(pinv)
np.round(np.linalg.pinv(A), 3)

# approx = np.zeros_like(A)
# for i in range(2):
#     approx = approx + (S[i] * np.outer(U[:,i], VT[i,:].T))
# print(approx)

[[0. 1.]
 [1. 0.]
 [0. 1.]]


array([[0. , 0.5],
       [1. , 0. ],
       [0. , 0.5]])

In [ ]:
print(-10/13, -11/13)

-0.7692307692307693 -0.8461538461538461


In [ ]:
import scipy as sp
A = np.array([
    [0, 1, -1],
    [0, 1, 1],
    [1, 1, 1]
])


np.linalg.svd(A)

(array([[ 1.11022302e-16, -1.00000000e+00,  2.22044605e-16],
        [-6.15412209e-01, -2.35513869e-16, -7.88205438e-01],
        [-7.88205438e-01,  0.00000000e+00,  6.15412209e-01]]),
 array([2.13577921, 1.41421356, 0.66215345]),
 array([[-0.36904818, -0.6571923 , -0.6571923 ],
        [ 0.        , -0.70710678,  0.70710678],
        [ 0.92941026, -0.26095647, -0.26095647]]))

In [ ]:
q1 = np.array([1,2,-2])
v2 = np.array([0.707,0.707,0])
v3 = np.array([-1, 1, 1])

q2 = v2 - np.dot(q1, v2)*q1
q2 = q2/np.linalg.norm(q2)

q3 = (v3 - np.dot(q1, v3)*q1 - np.dot(q2, v3)*q1)
q3 = q3/np.linalg.norm(q3)
# q3 = np.array([-1, 0, 0])

q1 = np.array([1, 2, -2])
q2 = np.array([0, 1, 1])
q3 = np.cross(q1, q2)

print(q3)
print(np.dot(q1, q2))
print(np.dot(q1, q3))
print(np.dot(q2, q3))

[ 4 -1  1]
0
0
0


In [ ]:
Q = np.array([
    [5, -4],
    [4, 5]
])
mag = (5**2 + 4**2)**0.5
Q = Q/mag
print("Q", Q)

D = np.diag([1, 2])

A = Q@D@Q.T
print(A@np.array([5, 4]))
print(A@np.array([-4, 5]))

q1 = np.array([ 0.78086881, -0.62469505])
q2 = np.array([ 0.62469505,  0.78086881])
q1@q2


Q [[ 0.78086881 -0.62469505]
 [ 0.62469505  0.78086881]]
[5. 4.]
[-8. 10.]


0.0

In [ ]:
Q = np.array([
    [1, -1, 1],
    [-1, -1, 1],
    [-1, -1 , -1]
])
mag = 3**0.5
Q = Q / mag
D = np.diag([0, 1, 0.2])

A = Q@D@Q.T
print(np.linalg.eig(A))

An = A.copy()
for i in range(100):
    An = An @ A


v = 2*np.array([1, -1, -1]) + 2*np.array([-1, -1, -1]) + 1*np.array([1, 1, -1])
print(A@v)

(array([1.02687495e+00, 2.50799698e-17, 1.73125051e-01]), array([[-6.05912800e-01, -7.07106781e-01, -3.64512933e-01],
       [-6.05912800e-01,  7.07106781e-01, -3.64512933e-01],
       [-5.15499134e-01,  6.15886491e-17,  8.56890100e-01]]))
[-2.13333333 -2.13333333 -2.53333333]


In [ ]:
b2 = 1/np.sqrt(2) * np.array([-1, 0, 1])
v = np.array([0, 0, 1])

np.dot(b2, v)

0.7071067811865475

In [ ]:
10+9+8+7+6+5+4+3+2+1

55

In [ ]:
A = np.array([
    [1, 0, 1, -1],
    [0, 1, 1, -1],
    [0, 1, 0, 1],
    [1, 1, 1, 1]

])

b = np.array([-2, 2, 0, 4])

x = np.linalg.solve(A, b)

print(x)
# print(A @ inv)



[-10.  -6.  14.   6.]


In [ ]:
-9/4

-2.25

In [ ]:
from sympy import Matrix


M = Matrix([
    [-2, 4, 2],
    [4, 0, 4],
    [6, 2, 8],
    [-8, -2, -10],
    [-4, 6, 2]
])

M.rref()

(Matrix([
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0]]),
 (0, 1))