In [145]:
import numpy as np

n = 1000000
p = 0.24

#A is the prob that a fails. 0 means success and 1 is fail
A = np.random.choice([0, 1], p=[1-p, p], size=n)
B = np.random.choice([0, 1], p=[1-p, p], size=n)
C = np.random.choice([0, 1], p=[1-p, p], size=n)

passes = 0
passandcfail = 0

for i in range(len(A)):
    if((not A[i] and not B[i]) or not C[i]):
        passes += 1
        if(C[i]):
            passandcfail += 1
    

print(passandcfail/n)
print(passes/n)

print(passandcfail/passes)



0.138398
0.89855
0.1540237048578265


In [232]:
import numpy as np

trials = 10000
good = 0
tickets = 219
prob_attend = 0.9

for i in range(trials):
    attendees = np.random.choice([0, 1], p=[1-prob_attend, prob_attend], size=tickets)
    if sum(attendees) <= 200:
        good += 1

print(good/trials)

0.7763


In [25]:
from math import pi, sqrt
import numpy as np
from numpy import sin, cos
from scipy.linalg import expm


sqrt3 = sqrt(3)/3
w = np.array([
    [0, -sqrt(3)/3, sqrt(3)/3],
    [sqrt(3)/3, 0, -sqrt(3)/3],
    [-sqrt(3)/3, sqrt(3)/3, 0]
])

theta = pi

x = (theta*np.eye(3) + (1-cos(theta))*w + (theta-sin(theta))*(w@w)) @ np.array([1, 1, 1])

np.round(x, 2)

# S = np.array()

array([3.14, 3.14, 3.14])

In [26]:
expm(theta*w)

array([[-0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667, -0.33333333,  0.66666667],
       [ 0.66666667,  0.66666667, -0.33333333]])

In [ ]:
epis = np.array([
    [-1/3, 2/3, 2/3, pi],
    [2/3, -1/3, 2/3, pi],
    [2/3, 2/3, -1/3, pi],
    [0, 0, 0, 1]
])


In [14]:
Tsb = np.array([
    [0, 1, 0, 0],
    [-1, 0, 0, -2],
    [0, 0, 1, -2],
    [0, 0, 0, 1]
])

Tsa = np.array([
    [0, 0, 1, -3],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
])

np.linalg.inv(Tsb)@Tsa

array([[-1.,  0.,  0., -2.],
       [ 0.,  0.,  1., -3.],
       [ 0.,  1.,  0.,  2.],
       [ 0.,  0.,  0.,  1.]])

In [27]:
Tsa@Tsa

array([[ 0,  1,  0, -3],
       [ 0,  0,  1, -3],
       [ 1,  0,  0,  0],
       [ 0,  0,  0,  1]])

In [24]:
R = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

theta = np.arccos(1/2*(np.trace(R) - 1))
w1 = 1/(2*(sin(theta)))
w2 = 1/(2*(sin(theta)))
w3 = 1/(2*(sin(theta)))
# print(w1, w2, w3)

w=1/(2*sin(theta)) * (R - R.T)

v = (1/theta * np.eye(3) - 1/2*w - (1/theta - 1/2*(1/np.tan(theta/1)))*(w@w))@np.array([-3, 0, 0])
v

array([-2.96467442,  1.63216537, -0.09988544])