In [1]:
import numpy as np
from numpy import sin, cos, tan, pi, arccos, arcsin, sqrt, radians, degrees
from scipy.linalg import expm, logm
import matplotlib.pyplot as plt
from fractions import Fraction

from util import *

np.set_printoptions(precision=3, suppress=True)

In [2]:
w = [0, 0.866, 0.5]
theta = radians(180)
R = get_rotation_from_axis_angle(axis=skew(w), angle=theta)
print(R)
W, theta = get_axis_angle_from_rotation(R)
print(W, unskew(W), degrees(theta))

[[-1.    -0.     0.   ]
 [ 0.     0.5    0.866]
 [-0.     0.866 -0.5  ]]
there are 6 solutions for W
[[ 0.    -0.5    0.866]
 [ 0.5    0.    -0.   ]
 [-0.866  0.     0.   ]] [0.    0.866 0.5  ] 180.0


In [3]:
#example 3.23, the tricycle
R_sb = np.array([ #car frame rotation in space frame
    [-1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
])
p_sb = np.array((4, 0.4, 0)) #position of car in space frame
r_s = np.array((2, -1, 0))
T_sb = format_transformation(R_sb, p_sb)
r_b = transform_point(np.linalg.inv(T_sb), r_s)
w_s = np.array((0, 0, 2))
w_b = np.array((0, 0, -2))
v_s = cross(r_s, w_s)       #v = r x ω
v_b = cross(r_b, w_b)
twist_s = np.concatenate((w_s, v_s))
twist_b = np.concatenate((w_b, v_b))
print(f"twist_s: {twist_s}, twist_b: {twist_b}")
Adj_Tsb = adjoint(T_sb)
print(Adj_Tsb @ twist_b)    #show that Adj can convert body twist to space twist

twist_s: [ 0  0  2 -2 -4  0], twist_b: [ 0.   0.  -2.   2.8  4.   0. ]
[ 0.  0.  2. -2. -4.  0.]


In [4]:
print(get_twist_from_screw_qsh(2, (0, 1, 0), (0, 0, 1), 0))

[0. 0. 2. 2. 0. 0.]


In [5]:
s = (0, 0, 1, 3.37, -3.37, 0)
T = get_transformation_from_screw_axis_angle(s, radians(30))
print(T)

S, theta = get_screw_axis_angle_from_transformation(T)
s = extract_twist_vector_from_matrix(S)
print(s, degrees(theta))

[[ 0.866 -0.5    0.     2.136]
 [ 0.5    0.866  0.    -1.234]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]
[ 0.    0.    1.    3.37 -3.37  0.  ] 29.99999999999998
