In [3]:
from casadi import *

In [74]:
p = SX.sym('p')
q = SX.sym('q')
r = SX.sym('r')
f = Function('f',
    [p, q, r],
    [
        1*p+2*sin(q)+3*cos(r),
        2*p+3*sin(q)+2*cos(r),
        3*p+1*sin(q)+1*cos(r)
    ],
    ['p', 'q', 'r'],
    ['x', 'y', 'z']
)

jac = f.jacobian_old(0, 0)

print(f)
print(jac)

f:(p,q,r)->(x,y,z) SXFunction
f_jac:(p,q,r)->(jac_x_p,x,y,z) SXFunction


In [72]:
display(jac)

Function(f_jac:(p,q,r)->(jac_x_p,x,y,z) SXFunction)

In [52]:
jac_eval = jac(2, 3, 3, 2, 3, 4)
print('jac_eval:', jac_eval)

print(np.array(jac(2, 3, 3, 2, 3, 4)))


jac_eval: 
[[1, -1.97998, -0.42336], 
 [2, -2.96998, -0.28224], 
 [3, -0.989992, -0.14112]]
[[ 1.         -1.97998499 -0.42336002]
 [ 2.         -2.96997749 -0.28224002]
 [ 3.         -0.9899925  -0.14112001]]


In [51]:
display(f)

Function(f:(p,q,r)->(x,y,z) SXFunction)

In [67]:
t = SX.sym("t")
d = SX.sym("d")

p = SX.zeros(2,1)

p[1,0] = 1/(1+exp(-(t-d)))

p[0,0] = 1 - p[1,0]

f = Function('f',
    [t,d],
    [p]
)

f.jacobian_old()

NotImplementedError: Wrong number or type of arguments for function 'Function_jacobian_old'.
  Prototype:
jacobian_old(self,int,int)
  You have: 


In [77]:
x = SX.sym('x')
y = SX.sym('y')
x**6/y*y**3/x/x/x/x/y/y/x/x

SX(((((((((((sq((x*sq(x)))/y)*(y*sq(y)))/x)/x)/x)/x)/y)/y)/x)/x))