In [1]:
import numpy as np
import scipy
from sympy import *
import matplotlib.pyplot as plt
%matplotlib widget
init_printing(use_unicode=True)

In [6]:
x, y = symbols('x y')

eq1 = sin(2*x+y+pi/2)
eq2 = sin(3*x+2*y-pi/3)

jacobians = []
pts = [[2*pi/3, 5*pi/3], [pi/6, 7*pi/6]]
for x_pt in pts[0]:
    for y_pt in pts[1]:
        jac = np.zeros((2,2))
        jac[0,0] = diff(eq1, x).subs({'x':x_pt, 'y':y_pt})
        jac[0,1] = diff(eq1, y).subs({'x':x_pt, 'y':y_pt})
        jac[1,0] = diff(eq2, x).subs({'x':x_pt, 'y':y_pt})
        jac[1,1] = diff(eq2, y).subs({'x':x_pt, 'y':y_pt})
        jacobians.append(jac)
        

jacobians

[array([[2., 1.],
        [3., 2.]]),
 array([[-2., -1.],
        [ 3.,  2.]]),
 array([[ 2.,  1.],
        [-3., -2.]]),
 array([[-2., -1.],
        [-3., -2.]])]

In [7]:
np.linalg.eigvals(jacobians)


array([[ 3.73205081,  0.26794919],
       [-1.        ,  1.        ],
       [ 1.        , -1.        ],
       [-0.26794919, -3.73205081]])

In [20]:
for K in np.arange(-10, 10):
    A = np.array([
        [1+K/2, K/2],
        [K/2, 2+K/2]
    ])
    print(K, np.linalg.eigvals(A))

-10 [-8.52493781  1.52493781]
-9 [-7.52769257  1.52769257]
-8 [-6.53112887  1.53112887]
-7 [-5.53553391  1.53553391]
-6 [-4.54138127  1.54138127]
-5 [-3.54950976  1.54950976]
-4 [-2.56155281  1.56155281]
-3 [-1.58113883  1.58113883]
-2 [-0.61803399  1.61803399]
-1 [0.29289322 1.70710678]
0 [1. 2.]
1 [1.29289322 2.70710678]
2 [1.38196601 3.61803399]
3 [1.41886117 4.58113883]
4 [1.43844719 5.56155281]
5 [1.45049024 6.54950976]
6 [1.45861873 7.54138127]
7 [1.46446609 8.53553391]
8 [1.46887113 9.53112887]
9 [ 1.47230743 10.52769257]


In [11]:
K, l = symbols('K l')
expr = (1 + K/2 - l)*(K/2 + 2 - l) - K**2/4
poly(expr)

In [19]:
solve(expr.subs({'K': -4/3}), l)