In [2]:
import numpy as np
from numpy import sin, cos, tan, pi, arccos, arcsin, sqrt
from scipy.linalg import expm, logm
import matplotlib.pyplot as plt
from fractions import Fraction

from util import *

np.set_printoptions(precision=3, suppress=True)

In [5]:
R = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])
theta=2*pi/3
get_S_theta(R, theta)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
omega = np.array([1, 1, 1]) * sqrt(3)/3
v = np.array([1, 1, 1])
theta = pi

S = get_screw(omega, v)

T = expm(S*theta)
T@origin

array([[-0.333,  0.667,  0.667,  3.142],
       [ 0.667, -0.333,  0.667,  3.142],
       [ 0.667,  0.667, -0.333,  3.142],
       [-0.   ,  0.   , -0.   ,  1.   ]])

In [ ]:
Tsa = np.array([
    [0, 0, 1, 3],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
])

logm(Tsa)

array([[-0.   , -1.209,  1.209,  2.209],
       [ 1.209,  0.   , -1.209, -1.418],
       [-1.209,  1.209,  0.   ,  2.209],
       [ 0.   ,  0.   ,  0.   ,  0.   ]])

In [ ]:
-np.cross([0, 1, 0], [-1, 1, 0])

array([ 0,  0, -1])