In [2]:
import numpy as np
import sympy


In [6]:
J_A = np.array([
    [-3, 0, 0],
    [0, 0, 0],
    [0, 2, 1]
])

J_A.T@J_A

array([[9, 0, 0],
       [0, 4, 2],
       [0, 2, 1]])

In [7]:
J_B = np.array([
    [0, 0, 0],
    [0, -1, 0],
    [0, -1, -1]
])

J_B.T@J_B

array([[0, 0, 0],
       [0, 2, 1],
       [0, 1, 1]])

In [10]:
from sympy import *

T = symbols('T')
a5, a4, a3 = symbols('a5 a4 a3')

res = linsolve(Matrix(([T**5, T**4, T**3, 1], [5*T**4, 4*T**3, 3*T**2, 0], [20*T**3, 12*T**2, 6*T, 1])), (a5, a4, a3))

In [19]:
a5 = res.args[0][0]
a4 = res.args[0][1]
a3 = res.args[0][2]

In [27]:
expr = (-4*a4+sqrt(16*a4**2-4*10*a5*a3))/(2*10*a5)
simplify(expr)

T*(sqrt(2)*T**4*sqrt((3*T**4 + 80*T**2 + 600)/T**8) + 4*T**2 + 60)/(10*(T**2 + 12))

In [28]:
expr.subs({T:3.1})

2.23517672626098

In [23]:
expr = (-4*a4-sqrt(16*a4**2-4*10*a5*a3))/(2*10*a5)
simplify(expr)

T*(-sqrt(2)*T**4*sqrt((3*T**4 + 80*T**2 + 600)/T**8) + 4*T**2 + 60)/(10*(T**2 + 12))

In [25]:
expr.subs({T:3.1})

0.589108326955126

In [30]:
A = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [-3, -5, -3]
])
np.linalg.eigvals(A)

array([-1.+0.j        , -1.+1.41421356j, -1.-1.41421356j])